apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ro97e9yam-python
  janus-idp.io/tekton: ro97e9yam-python
  backstage.io/kubernetes-id: ro97e9yam-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ro97e9yam-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
